name: Scheduled Firestore Comparison

on:
  schedule:
    - cron: "30 12 * * *"  # 6 PM IST = 12:30 UTC
  workflow_dispatch:       # Allow manual trigger

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger /manual-compare endpoint
        run: |
          curl -X GET https://stock-predictor-backend-4tp3.onrender.com/manual-compare
